export default {
	state:{
		footer_nav:[
			{
				name:'首页',
				name_code:'home',
				icon:'home',
				select_icon:'home-filled',
				size:'small'
			},
			{
				name:'附近',
				name_code:'nearby',
				icon:'location',
				select_icon:'location-filled',
				size:'small'
			},
			{
				name:'购物车',
				name_code:'shopCart',
				icon:'plus',
				select_icon:'plus-filled',
				size:'small'
			},
			{
				name:'我的',
				name_code:'mine',
				icon:'person',
				select_icon:'person-filled',
				size:'small'
			}
			
		],
		now_page_index:0,
		footer_nav_len: 4
	},
	mutations:{
		change_nav_list(state,data){
			state.footer_nav = data;
		},
		change_page(state,index){
			state.now_page_index = index;
		},
		change_nav_len(state, len){
			state.footer_nav_len = len;
		}
	},
	actions:{
		menu_4(ctx){
			let menu_list = [
				{
					name:'首页',
					name_code:'home',
					icon:'home',
					select_icon:'home-filled',
					size:'small'
				},
				{
					name:'附近',
					name_code:'nearby',
					icon:'location',
					select_icon:'location-filled',
					size:'small'
				},
				{
					name:'购物车',
					name_code:'shopCart',
					icon:'plus',
					select_icon:'plus-filled',
					size:'small'
				},
				{
					name:'我的',
					name_code:'mine',
					icon:'person',
					select_icon:'person-filled',
					size:'small'
				}
			]
			
			ctx.commit("change_nav_list",menu_list)
		},
		menu_5(ctx){
			let menu_list = [
				{
					name:'首页',
					name_code:'home',
					icon:'home',
					select_icon:'home-filled',
					size:'small'
				},
				{
					name:'附近',
					name_code:'nearby',
					icon:'location',
					select_icon:'location-filled',
					size:'small'
				},
				{
					name:'会员中心',
					name_code:'vipCenter',
					icon:'star',
					select_icon:'star-filled',
					size:'small'
				},
				{
					name:'购物车',
					name_code:'shopCart',
					icon:'plus',
					select_icon:'plus-filled',
					size:'small'
				},
				{
					name:'我的',
					name_code:'mine',
					icon:'person',
					select_icon:'person-filled',
					size:'small'
				}
			]
			
			ctx.commit("change_nav_list",menu_list)
		}
	}
}